### PR TITLE
Add some help and instructions to startup wizard.

### LINKED ISSUE #25: The initial connection screen could use some instructions
It isn't clear from the initial connection screen that btcd has to be running and that I'm entering the credentials for it.

This could be cleared up pretty easily I think with some instructions at the top of the dialog.

### LINKED ISSUE #26: A public wallet passphrase is requested even when there isn't one
I understand that currently there probably isn't a gRPC to query if a public passphrase is needed, but ideally there should be one added.  It is confusing to request a passphrase when there isn't one.

In the mean time, I think some instructions at the top of the dialog to clarify the situation would go a long way to clearing up the confusion.  Perhaps something like the following:

A public passphrase is only required if you chose to encrypt public data when creating the wallet.  Simply click Open Wallet if you did not encrypt public data.

### PR DESCRIPTION
**Pull request by jrick**
Fixes #25.

Fixes #26.

### CODE REVIEW

**Comment by jrick** [comment]
Alternatively, for the public passphrase prompt, instead of saying "click Open wallet", it could say "simply continue by opening the wallet with an empty public passphrase".  Then we could remove the ugly underline.

**Comment by jrick** [comment]
Also, it's possible to set a public encryption passphrase later, so "when creating" is not technically correct here either.

**Comment by davecgh** [comment]
OK

**Comment by davecgh** [comment]
OK

**Pull request merged**
