### PR TITLE
Use Paymetheus' local AppData directory for wallet.

### LINKED ISSUE #52: Use Paymetheus application data directory for wallet data
Paymetheus should execute the wallet process with the --datadir option to set an alternate application data directory for wallet to write its data to (most importantly, the wallet DB and RPC cert).  This will make Paymetheus appear more as a standalone product as it won't have any unusual interaction from an already existing wallet datadir (such as failing to start due to an already existing rpc.key, which breaks the --onetimetlskey option used by Paymetheus).

### PR DESCRIPTION
**Pull request by jrick**
Add AssemblyResources static class for reading attributes from the
entry assembly.  This is used to access the name of the application
which is used for the local appdata directory.

Fixes #52.

### CODE REVIEW

**Comment by davecgh** [comment]
I like the concept.  I do see a potential issue here with ports since they're also named "Paymetheus".  I could see there being a problem where it tries to use the same directory for two different coins based on it.

The code itself looks fine.

**Comment by davecgh** [comment]
Code itself looks fine.

**Comment by davecgh** [comment]
Discussed on IRC.  This just means the ports will need to be named something like "Paymetheus-whatever".

**Comment by jrick** [comment]
Updated again and could use another code review.  It now includes the organization name (so the local appdata dir becomes AppData\Btcsuite\Paymetheus).  This means that forks for other currencies only need to change the organization name, rather than modifying the product name to avoid a conflict.

A new metadata attribute for the organization was added instead of modifying the company, in case we want to use Company 0 as the company in the future.

Also fixed a bug where spaces in the btcwallet datadir path would cause hangs at startup because it would use the wrong directory and the filesystem watcher for the rpc certificate would never complete.

**Comment by davecgh** [comment]
OK

**Pull request merged**
