### PR TITLE
Add method to import seed when creating a wallet.

### LINKED ISSUE #24: No way to import an existing seed.
Unless it is hidden somewhere, I don't see any way to import an existing seed.  A new seed is automatically created and prompted.

### PR DESCRIPTION
**Pull request by jrick**
This only adds the dialog and will call the CreateNewWallet RPC with
the decoded seed rather than a randomly-generated one.

As btcwallet does not support recovering addresses and transactions
for an imported seed, this feature won't work correctly and
transaction history will have to be recovered after generating the
same number of addresses used from the previous wallet.  However, once
that is implemented, this GUI feature should work as intended.

The seed can be inputed using either hex or the PGP word list
encoding.  At the moment, no checksumming is used or removed from the
input, and all bytes are considered part of the seed.  If any
additional data is added to a seed encoding later, the
WalletSeed.DecodeAndValidateUserInput method will need to be changed
to interpret this separately.

Closes #24.

### CODE REVIEW

**Comment by jrick** [comment]
Obviously this feature will have little use currently for Bitcoin Paymetheus since the required parts of btcwallet are not done yet, however, it will be useful for the Decred fork.

**Comment by jrick** [comment]
Screenshots of the new dialogs: http://imgur.com/a/6jGml

**Comment by davecgh** [comment]
I personally think the description text should go below the selected radio button.  That is the typical way it is done.  I find it confusing to be under the unselected radio button.

**Comment by jrick** [comment]
Doing it this way means that the bottom radio button doesn't jump around depending on whether the top button is selected or not, making the UI more consistent.  We would need some kind of visual animations added for showing or unhiding those details if they're shown directly under the selected radio button so the user isn't confused by the radio button's changing location.  It also allows the content area for the seed and seed prompt to be shared for both cases.

The radio buttons might be replaced with something else later, perhaps two buttons aligned horizontally across the top.

**Comment by jrick** [comment]
new look: http://i.imgur.com/CDS7bES.png

**Comment by davecgh** [comment]
Code reads fine.  I really don't like the text under both radio buttons as previously mentioned, but that shouldn't hold up the PR.

OK

**Pull request merged**
